spring:
  application:
    name: greeenai

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  jwt:
    token:
      access-token:
        secret: ${JWT_ACCESS_TOKEN_SECRET}
        expiration-time: 1800
      refresh-token:
        secret: ${JWT_REFRESH_TOKEN_SECRET}
        expiration-time: 172800
    issuer: ${JWT_ISSUER}